#!/bin/bash

# launch script for vsss I Prefer a Terminatorfor this
## but xterm/rxvterm should work
CMDP=./vsss_cmd.sh

ms_getpid="qdbus org.marnold.mklip /org/marnold/mklip getPid"

$ms_getpid > /dev/null
if [ $? -ne 0 ]
then
  ./mklip.py
  $CMDP
else
   $CMDP
fi
