#!/bin/bash

# launch script for vsss I Prefer a 9term window for this
## but xterm/rxvterm should work just as welljust don'tt use
## The terminals that come with the modern desktop envs
## they try to be to smart, and make controling just about any 
## Speech synth hell

# And because KDE is so stupid, we yet again 
PLAN9=/usr/local/plan9 export PLAN9
PATH=$PATH:$PLAN9/bin export PATH
CMDP=./vsss_cmd.sh
d_font=$PLAN9/font/times/latin1.bold.10.font 
p_font=/tmp/9fnt/Prestige\ Elite\ Normal/20

9p ls font > /dev/null
if [ $? -eq 1 ]
then
	mkdir -p /tmp/9fnt
	fontsrv -m /tmp/9fnt &
	font=$p_font export font
elif [ $? -eq 127 ]
then
	echo "Error no font server found reverting to ugly"
	font=$d_font export font
else
	font=$p_font export font
fi
9term   $CMDP

